version: "3.8"
services:
  php:
    build: './src/php'
    volumes:
      - ./src/www/:/var/www/html/

  apache:
    build: './src/apache'
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./src/www/:/var/www/html/

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

volumes:
  mysqldata:

